### ISSUE TITLE
request

### ISSUE THREAD

**Issue by cryptominecrafter** [luphoria/UBer#10]
TDLR: My school blocked all bookmarklets, request for proxy website?
Whole thing: (deleted)

**Comment by cryptominecrafter** [comment]
LMAO sorry, I meant "TLDR"

**Comment by luphoria** [comment]
Sorry, however UBer's entire purpose is to function as a bookmarklet.
Feel free to check out TitaniumNetwork's discord server (discord.gg/unblock) for proxy sites
