### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by cryptominecrafter** [luphoria/UBer#6]
Hi. So I have been using this for school for awhile now to unblock games and such, but I have just noticed today that whenever I click the bookmarklet nothing happens. I have no idea whether my school tech people are actually being smart and blocking the use of bookmarklets, but my Youtube volume bookmarklets work. I believe luphoria.com used to exist, but I'm not sure. It's currently down. So I don't know if this on your side or mine but I need help. Thanks.

**Comment by luphoria** [comment]
conversation moving to #7
