### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by ErrorChromebook** [luphoria/UBer#7]
This is honestly my last hope for unblocking stuff

**Comment by luphoria** [comment]
"no longer working"? elaborate?

**Comment by Duckfriend505** [comment]
it won't work at all the site is down

**Comment by cryptominecrafter** [comment]
I think I'm having the same issue. I created an issue if you want more info about the problem.

**Comment by ErrorChromebook** [comment]
I mea when I run the command using the bookmark, nothing happens

**Comment by luphoria** [comment]
Issue is with my actual website being down. This should be fixed momentarily

**Comment by luphoria** [comment]
Everything should be back now :smile:
